/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SponsorsEmbedImport } from './routes/sponsors-embed'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as LangLibrariesRouteImport } from './routes/$lang/_libraries/route'
import { Route as LangLibraryIdRouteImport } from './routes/$lang/$libraryId/route'
import { Route as LangLibrariesIndexImport } from './routes/$lang/_libraries/index'
import { Route as LangLibraryIdIndexImport } from './routes/$lang/$libraryId/index'
import { Route as LangLibrariesTermsImport } from './routes/$lang/_libraries/terms'
import { Route as LangLibrariesSupportImport } from './routes/$lang/_libraries/support'
import { Route as LangLibrariesPrivacyImport } from './routes/$lang/_libraries/privacy'
import { Route as LangLibrariesMerchImport } from './routes/$lang/_libraries/merch'
import { Route as LangLibrariesLearnImport } from './routes/$lang/_libraries/learn'
import { Route as LangLibrariesEthosImport } from './routes/$lang/_libraries/ethos'
import { Route as LangLibrariesDedicatedSupportImport } from './routes/$lang/_libraries/dedicated-support'
import { Route as LangLibrariesBlogImport } from './routes/$lang/_libraries/blog'
import { Route as LangLibraryIdVersionImport } from './routes/$lang/$libraryId/$version'
import { Route as LangLibrariesBlogIndexImport } from './routes/$lang/_libraries/blog.index'
import { Route as LangLibrariesBlogSplatImport } from './routes/$lang/_libraries/blog.$'
import { Route as LangLibraryIdVersionDocsImport } from './routes/$lang/$libraryId/$version.docs'
import { Route as LangLibrariesVirtualVersionIndexImport } from './routes/$lang/_libraries/virtual.$version.index'
import { Route as LangLibrariesTableVersionIndexImport } from './routes/$lang/_libraries/table.$version.index'
import { Route as LangLibrariesStoreVersionIndexImport } from './routes/$lang/_libraries/store.$version.index'
import { Route as LangLibrariesStartVersionIndexImport } from './routes/$lang/_libraries/start.$version.index'
import { Route as LangLibrariesRouterVersionIndexImport } from './routes/$lang/_libraries/router.$version.index'
import { Route as LangLibrariesRangerVersionIndexImport } from './routes/$lang/_libraries/ranger.$version.index'
import { Route as LangLibrariesQueryVersionIndexImport } from './routes/$lang/_libraries/query.$version.index'
import { Route as LangLibrariesFormVersionIndexImport } from './routes/$lang/_libraries/form.$version.index'
import { Route as LangLibrariesConfigVersionIndexImport } from './routes/$lang/_libraries/config.$version.index'
import { Route as LangLibraryIdVersionDocsIndexImport } from './routes/$lang/$libraryId/$version.docs.index'
import { Route as LangLibraryIdVersionDocsSplatImport } from './routes/$lang/$libraryId/$version.docs.$'
import { Route as LangLibraryIdVersionDocsFrameworkFrameworkSplatImport } from './routes/$lang/$libraryId/$version.docs.framework.$framework.$'
import { Route as LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatImport } from './routes/$lang/$libraryId/$version.docs.framework.$framework.examples.$'

// Create Virtual Routes

const LangImport = createFileRoute('/$lang')()

// Create/Update Routes

const LangRoute = LangImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRoute,
} as any)

const SponsorsEmbedRoute = SponsorsEmbedImport.update({
  id: '/sponsors-embed',
  path: '/sponsors-embed',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LangLibrariesRouteRoute = LangLibrariesRouteImport.update({
  id: '/_libraries',
  getParentRoute: () => LangRoute,
} as any)

const LangLibraryIdRouteRoute = LangLibraryIdRouteImport.update({
  id: '/$lang/$libraryId',
  path: '/$lang/$libraryId',
  getParentRoute: () => rootRoute,
} as any)

const LangLibrariesIndexRoute = LangLibrariesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangLibrariesRouteRoute,
} as any)

const LangLibraryIdIndexRoute = LangLibraryIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangLibraryIdRouteRoute,
} as any)

const LangLibrariesTermsRoute = LangLibrariesTermsImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LangLibrariesRouteRoute,
} as any)

const LangLibrariesSupportRoute = LangLibrariesSupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => LangLibrariesRouteRoute,
} as any)

const LangLibrariesPrivacyRoute = LangLibrariesPrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangLibrariesRouteRoute,
} as any)

const LangLibrariesMerchRoute = LangLibrariesMerchImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => LangLibrariesRouteRoute,
} as any)

const LangLibrariesLearnRoute = LangLibrariesLearnImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => LangLibrariesRouteRoute,
} as any)

const LangLibrariesEthosRoute = LangLibrariesEthosImport.update({
  id: '/ethos',
  path: '/ethos',
  getParentRoute: () => LangLibrariesRouteRoute,
} as any)

const LangLibrariesDedicatedSupportRoute =
  LangLibrariesDedicatedSupportImport.update({
    id: '/dedicated-support',
    path: '/dedicated-support',
    getParentRoute: () => LangLibrariesRouteRoute,
  } as any)

const LangLibrariesBlogRoute = LangLibrariesBlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LangLibrariesRouteRoute,
} as any)

const LangLibraryIdVersionRoute = LangLibraryIdVersionImport.update({
  id: '/$version',
  path: '/$version',
  getParentRoute: () => LangLibraryIdRouteRoute,
} as any)

const LangLibrariesBlogIndexRoute = LangLibrariesBlogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangLibrariesBlogRoute,
} as any)

const LangLibrariesBlogSplatRoute = LangLibrariesBlogSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LangLibrariesBlogRoute,
} as any)

const LangLibraryIdVersionDocsRoute = LangLibraryIdVersionDocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => LangLibraryIdVersionRoute,
} as any)

const LangLibrariesVirtualVersionIndexRoute =
  LangLibrariesVirtualVersionIndexImport.update({
    id: '/virtual/$version/',
    path: '/virtual/$version/',
    getParentRoute: () => LangLibrariesRouteRoute,
  } as any)

const LangLibrariesTableVersionIndexRoute =
  LangLibrariesTableVersionIndexImport.update({
    id: '/table/$version/',
    path: '/table/$version/',
    getParentRoute: () => LangLibrariesRouteRoute,
  } as any)

const LangLibrariesStoreVersionIndexRoute =
  LangLibrariesStoreVersionIndexImport.update({
    id: '/store/$version/',
    path: '/store/$version/',
    getParentRoute: () => LangLibrariesRouteRoute,
  } as any)

const LangLibrariesStartVersionIndexRoute =
  LangLibrariesStartVersionIndexImport.update({
    id: '/start/$version/',
    path: '/start/$version/',
    getParentRoute: () => LangLibrariesRouteRoute,
  } as any)

const LangLibrariesRouterVersionIndexRoute =
  LangLibrariesRouterVersionIndexImport.update({
    id: '/router/$version/',
    path: '/router/$version/',
    getParentRoute: () => LangLibrariesRouteRoute,
  } as any)

const LangLibrariesRangerVersionIndexRoute =
  LangLibrariesRangerVersionIndexImport.update({
    id: '/ranger/$version/',
    path: '/ranger/$version/',
    getParentRoute: () => LangLibrariesRouteRoute,
  } as any)

const LangLibrariesQueryVersionIndexRoute =
  LangLibrariesQueryVersionIndexImport.update({
    id: '/query/$version/',
    path: '/query/$version/',
    getParentRoute: () => LangLibrariesRouteRoute,
  } as any)

const LangLibrariesFormVersionIndexRoute =
  LangLibrariesFormVersionIndexImport.update({
    id: '/form/$version/',
    path: '/form/$version/',
    getParentRoute: () => LangLibrariesRouteRoute,
  } as any)

const LangLibrariesConfigVersionIndexRoute =
  LangLibrariesConfigVersionIndexImport.update({
    id: '/config/$version/',
    path: '/config/$version/',
    getParentRoute: () => LangLibrariesRouteRoute,
  } as any)

const LangLibraryIdVersionDocsIndexRoute =
  LangLibraryIdVersionDocsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangLibraryIdVersionDocsRoute,
  } as any)

const LangLibraryIdVersionDocsSplatRoute =
  LangLibraryIdVersionDocsSplatImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => LangLibraryIdVersionDocsRoute,
  } as any)

const LangLibraryIdVersionDocsFrameworkFrameworkSplatRoute =
  LangLibraryIdVersionDocsFrameworkFrameworkSplatImport.update({
    id: '/framework/$framework/$',
    path: '/framework/$framework/$',
    getParentRoute: () => LangLibraryIdVersionDocsRoute,
  } as any)

const LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute =
  LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatImport.update({
    id: '/framework/$framework/examples/$',
    path: '/framework/$framework/examples/$',
    getParentRoute: () => LangLibraryIdVersionDocsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/sponsors-embed': {
      id: '/sponsors-embed'
      path: '/sponsors-embed'
      fullPath: '/sponsors-embed'
      preLoaderRoute: typeof SponsorsEmbedImport
      parentRoute: typeof rootRoute
    }
    '/$lang/$libraryId': {
      id: '/$lang/$libraryId'
      path: '/$lang/$libraryId'
      fullPath: '/$lang/$libraryId'
      preLoaderRoute: typeof LangLibraryIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangImport
      parentRoute: typeof rootRoute
    }
    '/$lang/_libraries': {
      id: '/$lang/_libraries'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangLibrariesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/$libraryId/$version': {
      id: '/$lang/$libraryId/$version'
      path: '/$version'
      fullPath: '/$lang/$libraryId/$version'
      preLoaderRoute: typeof LangLibraryIdVersionImport
      parentRoute: typeof LangLibraryIdRouteImport
    }
    '/$lang/_libraries/blog': {
      id: '/$lang/_libraries/blog'
      path: '/blog'
      fullPath: '/$lang/blog'
      preLoaderRoute: typeof LangLibrariesBlogImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/dedicated-support': {
      id: '/$lang/_libraries/dedicated-support'
      path: '/dedicated-support'
      fullPath: '/$lang/dedicated-support'
      preLoaderRoute: typeof LangLibrariesDedicatedSupportImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/ethos': {
      id: '/$lang/_libraries/ethos'
      path: '/ethos'
      fullPath: '/$lang/ethos'
      preLoaderRoute: typeof LangLibrariesEthosImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/learn': {
      id: '/$lang/_libraries/learn'
      path: '/learn'
      fullPath: '/$lang/learn'
      preLoaderRoute: typeof LangLibrariesLearnImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/merch': {
      id: '/$lang/_libraries/merch'
      path: '/merch'
      fullPath: '/$lang/merch'
      preLoaderRoute: typeof LangLibrariesMerchImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/privacy': {
      id: '/$lang/_libraries/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangLibrariesPrivacyImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/support': {
      id: '/$lang/_libraries/support'
      path: '/support'
      fullPath: '/$lang/support'
      preLoaderRoute: typeof LangLibrariesSupportImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/terms': {
      id: '/$lang/_libraries/terms'
      path: '/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangLibrariesTermsImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/$libraryId/': {
      id: '/$lang/$libraryId/'
      path: '/'
      fullPath: '/$lang/$libraryId/'
      preLoaderRoute: typeof LangLibraryIdIndexImport
      parentRoute: typeof LangLibraryIdRouteImport
    }
    '/$lang/_libraries/': {
      id: '/$lang/_libraries/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangLibrariesIndexImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/$libraryId/$version/docs': {
      id: '/$lang/$libraryId/$version/docs'
      path: '/docs'
      fullPath: '/$lang/$libraryId/$version/docs'
      preLoaderRoute: typeof LangLibraryIdVersionDocsImport
      parentRoute: typeof LangLibraryIdVersionImport
    }
    '/$lang/_libraries/blog/$': {
      id: '/$lang/_libraries/blog/$'
      path: '/$'
      fullPath: '/$lang/blog/$'
      preLoaderRoute: typeof LangLibrariesBlogSplatImport
      parentRoute: typeof LangLibrariesBlogImport
    }
    '/$lang/_libraries/blog/': {
      id: '/$lang/_libraries/blog/'
      path: '/'
      fullPath: '/$lang/blog/'
      preLoaderRoute: typeof LangLibrariesBlogIndexImport
      parentRoute: typeof LangLibrariesBlogImport
    }
    '/$lang/$libraryId/$version/docs/$': {
      id: '/$lang/$libraryId/$version/docs/$'
      path: '/$'
      fullPath: '/$lang/$libraryId/$version/docs/$'
      preLoaderRoute: typeof LangLibraryIdVersionDocsSplatImport
      parentRoute: typeof LangLibraryIdVersionDocsImport
    }
    '/$lang/$libraryId/$version/docs/': {
      id: '/$lang/$libraryId/$version/docs/'
      path: '/'
      fullPath: '/$lang/$libraryId/$version/docs/'
      preLoaderRoute: typeof LangLibraryIdVersionDocsIndexImport
      parentRoute: typeof LangLibraryIdVersionDocsImport
    }
    '/$lang/_libraries/config/$version/': {
      id: '/$lang/_libraries/config/$version/'
      path: '/config/$version'
      fullPath: '/$lang/config/$version'
      preLoaderRoute: typeof LangLibrariesConfigVersionIndexImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/form/$version/': {
      id: '/$lang/_libraries/form/$version/'
      path: '/form/$version'
      fullPath: '/$lang/form/$version'
      preLoaderRoute: typeof LangLibrariesFormVersionIndexImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/query/$version/': {
      id: '/$lang/_libraries/query/$version/'
      path: '/query/$version'
      fullPath: '/$lang/query/$version'
      preLoaderRoute: typeof LangLibrariesQueryVersionIndexImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/ranger/$version/': {
      id: '/$lang/_libraries/ranger/$version/'
      path: '/ranger/$version'
      fullPath: '/$lang/ranger/$version'
      preLoaderRoute: typeof LangLibrariesRangerVersionIndexImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/router/$version/': {
      id: '/$lang/_libraries/router/$version/'
      path: '/router/$version'
      fullPath: '/$lang/router/$version'
      preLoaderRoute: typeof LangLibrariesRouterVersionIndexImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/start/$version/': {
      id: '/$lang/_libraries/start/$version/'
      path: '/start/$version'
      fullPath: '/$lang/start/$version'
      preLoaderRoute: typeof LangLibrariesStartVersionIndexImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/store/$version/': {
      id: '/$lang/_libraries/store/$version/'
      path: '/store/$version'
      fullPath: '/$lang/store/$version'
      preLoaderRoute: typeof LangLibrariesStoreVersionIndexImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/table/$version/': {
      id: '/$lang/_libraries/table/$version/'
      path: '/table/$version'
      fullPath: '/$lang/table/$version'
      preLoaderRoute: typeof LangLibrariesTableVersionIndexImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/_libraries/virtual/$version/': {
      id: '/$lang/_libraries/virtual/$version/'
      path: '/virtual/$version'
      fullPath: '/$lang/virtual/$version'
      preLoaderRoute: typeof LangLibrariesVirtualVersionIndexImport
      parentRoute: typeof LangLibrariesRouteImport
    }
    '/$lang/$libraryId/$version/docs/framework/$framework/$': {
      id: '/$lang/$libraryId/$version/docs/framework/$framework/$'
      path: '/framework/$framework/$'
      fullPath: '/$lang/$libraryId/$version/docs/framework/$framework/$'
      preLoaderRoute: typeof LangLibraryIdVersionDocsFrameworkFrameworkSplatImport
      parentRoute: typeof LangLibraryIdVersionDocsImport
    }
    '/$lang/$libraryId/$version/docs/framework/$framework/examples/$': {
      id: '/$lang/$libraryId/$version/docs/framework/$framework/examples/$'
      path: '/framework/$framework/examples/$'
      fullPath: '/$lang/$libraryId/$version/docs/framework/$framework/examples/$'
      preLoaderRoute: typeof LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatImport
      parentRoute: typeof LangLibraryIdVersionDocsImport
    }
  }
}

// Create and export the route tree

interface LangLibraryIdVersionDocsRouteChildren {
  LangLibraryIdVersionDocsSplatRoute: typeof LangLibraryIdVersionDocsSplatRoute
  LangLibraryIdVersionDocsIndexRoute: typeof LangLibraryIdVersionDocsIndexRoute
  LangLibraryIdVersionDocsFrameworkFrameworkSplatRoute: typeof LangLibraryIdVersionDocsFrameworkFrameworkSplatRoute
  LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute: typeof LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute
}

const LangLibraryIdVersionDocsRouteChildren: LangLibraryIdVersionDocsRouteChildren =
  {
    LangLibraryIdVersionDocsSplatRoute: LangLibraryIdVersionDocsSplatRoute,
    LangLibraryIdVersionDocsIndexRoute: LangLibraryIdVersionDocsIndexRoute,
    LangLibraryIdVersionDocsFrameworkFrameworkSplatRoute:
      LangLibraryIdVersionDocsFrameworkFrameworkSplatRoute,
    LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute:
      LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute,
  }

const LangLibraryIdVersionDocsRouteWithChildren =
  LangLibraryIdVersionDocsRoute._addFileChildren(
    LangLibraryIdVersionDocsRouteChildren,
  )

interface LangLibraryIdVersionRouteChildren {
  LangLibraryIdVersionDocsRoute: typeof LangLibraryIdVersionDocsRouteWithChildren
}

const LangLibraryIdVersionRouteChildren: LangLibraryIdVersionRouteChildren = {
  LangLibraryIdVersionDocsRoute: LangLibraryIdVersionDocsRouteWithChildren,
}

const LangLibraryIdVersionRouteWithChildren =
  LangLibraryIdVersionRoute._addFileChildren(LangLibraryIdVersionRouteChildren)

interface LangLibraryIdRouteRouteChildren {
  LangLibraryIdVersionRoute: typeof LangLibraryIdVersionRouteWithChildren
  LangLibraryIdIndexRoute: typeof LangLibraryIdIndexRoute
}

const LangLibraryIdRouteRouteChildren: LangLibraryIdRouteRouteChildren = {
  LangLibraryIdVersionRoute: LangLibraryIdVersionRouteWithChildren,
  LangLibraryIdIndexRoute: LangLibraryIdIndexRoute,
}

const LangLibraryIdRouteRouteWithChildren =
  LangLibraryIdRouteRoute._addFileChildren(LangLibraryIdRouteRouteChildren)

interface LangLibrariesBlogRouteChildren {
  LangLibrariesBlogSplatRoute: typeof LangLibrariesBlogSplatRoute
  LangLibrariesBlogIndexRoute: typeof LangLibrariesBlogIndexRoute
}

const LangLibrariesBlogRouteChildren: LangLibrariesBlogRouteChildren = {
  LangLibrariesBlogSplatRoute: LangLibrariesBlogSplatRoute,
  LangLibrariesBlogIndexRoute: LangLibrariesBlogIndexRoute,
}

const LangLibrariesBlogRouteWithChildren =
  LangLibrariesBlogRoute._addFileChildren(LangLibrariesBlogRouteChildren)

interface LangLibrariesRouteRouteChildren {
  LangLibrariesBlogRoute: typeof LangLibrariesBlogRouteWithChildren
  LangLibrariesDedicatedSupportRoute: typeof LangLibrariesDedicatedSupportRoute
  LangLibrariesEthosRoute: typeof LangLibrariesEthosRoute
  LangLibrariesLearnRoute: typeof LangLibrariesLearnRoute
  LangLibrariesMerchRoute: typeof LangLibrariesMerchRoute
  LangLibrariesPrivacyRoute: typeof LangLibrariesPrivacyRoute
  LangLibrariesSupportRoute: typeof LangLibrariesSupportRoute
  LangLibrariesTermsRoute: typeof LangLibrariesTermsRoute
  LangLibrariesIndexRoute: typeof LangLibrariesIndexRoute
  LangLibrariesConfigVersionIndexRoute: typeof LangLibrariesConfigVersionIndexRoute
  LangLibrariesFormVersionIndexRoute: typeof LangLibrariesFormVersionIndexRoute
  LangLibrariesQueryVersionIndexRoute: typeof LangLibrariesQueryVersionIndexRoute
  LangLibrariesRangerVersionIndexRoute: typeof LangLibrariesRangerVersionIndexRoute
  LangLibrariesRouterVersionIndexRoute: typeof LangLibrariesRouterVersionIndexRoute
  LangLibrariesStartVersionIndexRoute: typeof LangLibrariesStartVersionIndexRoute
  LangLibrariesStoreVersionIndexRoute: typeof LangLibrariesStoreVersionIndexRoute
  LangLibrariesTableVersionIndexRoute: typeof LangLibrariesTableVersionIndexRoute
  LangLibrariesVirtualVersionIndexRoute: typeof LangLibrariesVirtualVersionIndexRoute
}

const LangLibrariesRouteRouteChildren: LangLibrariesRouteRouteChildren = {
  LangLibrariesBlogRoute: LangLibrariesBlogRouteWithChildren,
  LangLibrariesDedicatedSupportRoute: LangLibrariesDedicatedSupportRoute,
  LangLibrariesEthosRoute: LangLibrariesEthosRoute,
  LangLibrariesLearnRoute: LangLibrariesLearnRoute,
  LangLibrariesMerchRoute: LangLibrariesMerchRoute,
  LangLibrariesPrivacyRoute: LangLibrariesPrivacyRoute,
  LangLibrariesSupportRoute: LangLibrariesSupportRoute,
  LangLibrariesTermsRoute: LangLibrariesTermsRoute,
  LangLibrariesIndexRoute: LangLibrariesIndexRoute,
  LangLibrariesConfigVersionIndexRoute: LangLibrariesConfigVersionIndexRoute,
  LangLibrariesFormVersionIndexRoute: LangLibrariesFormVersionIndexRoute,
  LangLibrariesQueryVersionIndexRoute: LangLibrariesQueryVersionIndexRoute,
  LangLibrariesRangerVersionIndexRoute: LangLibrariesRangerVersionIndexRoute,
  LangLibrariesRouterVersionIndexRoute: LangLibrariesRouterVersionIndexRoute,
  LangLibrariesStartVersionIndexRoute: LangLibrariesStartVersionIndexRoute,
  LangLibrariesStoreVersionIndexRoute: LangLibrariesStoreVersionIndexRoute,
  LangLibrariesTableVersionIndexRoute: LangLibrariesTableVersionIndexRoute,
  LangLibrariesVirtualVersionIndexRoute: LangLibrariesVirtualVersionIndexRoute,
}

const LangLibrariesRouteRouteWithChildren =
  LangLibrariesRouteRoute._addFileChildren(LangLibrariesRouteRouteChildren)

interface LangRouteChildren {
  LangLibrariesRouteRoute: typeof LangLibrariesRouteRouteWithChildren
}

const LangRouteChildren: LangRouteChildren = {
  LangLibrariesRouteRoute: LangLibrariesRouteRouteWithChildren,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/sponsors-embed': typeof SponsorsEmbedRoute
  '/$lang/$libraryId': typeof LangLibraryIdRouteRouteWithChildren
  '/$lang': typeof LangLibrariesRouteRouteWithChildren
  '/$lang/$libraryId/$version': typeof LangLibraryIdVersionRouteWithChildren
  '/$lang/blog': typeof LangLibrariesBlogRouteWithChildren
  '/$lang/dedicated-support': typeof LangLibrariesDedicatedSupportRoute
  '/$lang/ethos': typeof LangLibrariesEthosRoute
  '/$lang/learn': typeof LangLibrariesLearnRoute
  '/$lang/merch': typeof LangLibrariesMerchRoute
  '/$lang/privacy': typeof LangLibrariesPrivacyRoute
  '/$lang/support': typeof LangLibrariesSupportRoute
  '/$lang/terms': typeof LangLibrariesTermsRoute
  '/$lang/$libraryId/': typeof LangLibraryIdIndexRoute
  '/$lang/': typeof LangLibrariesIndexRoute
  '/$lang/$libraryId/$version/docs': typeof LangLibraryIdVersionDocsRouteWithChildren
  '/$lang/blog/$': typeof LangLibrariesBlogSplatRoute
  '/$lang/blog/': typeof LangLibrariesBlogIndexRoute
  '/$lang/$libraryId/$version/docs/$': typeof LangLibraryIdVersionDocsSplatRoute
  '/$lang/$libraryId/$version/docs/': typeof LangLibraryIdVersionDocsIndexRoute
  '/$lang/config/$version': typeof LangLibrariesConfigVersionIndexRoute
  '/$lang/form/$version': typeof LangLibrariesFormVersionIndexRoute
  '/$lang/query/$version': typeof LangLibrariesQueryVersionIndexRoute
  '/$lang/ranger/$version': typeof LangLibrariesRangerVersionIndexRoute
  '/$lang/router/$version': typeof LangLibrariesRouterVersionIndexRoute
  '/$lang/start/$version': typeof LangLibrariesStartVersionIndexRoute
  '/$lang/store/$version': typeof LangLibrariesStoreVersionIndexRoute
  '/$lang/table/$version': typeof LangLibrariesTableVersionIndexRoute
  '/$lang/virtual/$version': typeof LangLibrariesVirtualVersionIndexRoute
  '/$lang/$libraryId/$version/docs/framework/$framework/$': typeof LangLibraryIdVersionDocsFrameworkFrameworkSplatRoute
  '/$lang/$libraryId/$version/docs/framework/$framework/examples/$': typeof LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/sponsors-embed': typeof SponsorsEmbedRoute
  '/$lang': typeof LangLibrariesIndexRoute
  '/$lang/$libraryId/$version': typeof LangLibraryIdVersionRouteWithChildren
  '/$lang/dedicated-support': typeof LangLibrariesDedicatedSupportRoute
  '/$lang/ethos': typeof LangLibrariesEthosRoute
  '/$lang/learn': typeof LangLibrariesLearnRoute
  '/$lang/merch': typeof LangLibrariesMerchRoute
  '/$lang/privacy': typeof LangLibrariesPrivacyRoute
  '/$lang/support': typeof LangLibrariesSupportRoute
  '/$lang/terms': typeof LangLibrariesTermsRoute
  '/$lang/$libraryId': typeof LangLibraryIdIndexRoute
  '/$lang/blog/$': typeof LangLibrariesBlogSplatRoute
  '/$lang/blog': typeof LangLibrariesBlogIndexRoute
  '/$lang/$libraryId/$version/docs/$': typeof LangLibraryIdVersionDocsSplatRoute
  '/$lang/$libraryId/$version/docs': typeof LangLibraryIdVersionDocsIndexRoute
  '/$lang/config/$version': typeof LangLibrariesConfigVersionIndexRoute
  '/$lang/form/$version': typeof LangLibrariesFormVersionIndexRoute
  '/$lang/query/$version': typeof LangLibrariesQueryVersionIndexRoute
  '/$lang/ranger/$version': typeof LangLibrariesRangerVersionIndexRoute
  '/$lang/router/$version': typeof LangLibrariesRouterVersionIndexRoute
  '/$lang/start/$version': typeof LangLibrariesStartVersionIndexRoute
  '/$lang/store/$version': typeof LangLibrariesStoreVersionIndexRoute
  '/$lang/table/$version': typeof LangLibrariesTableVersionIndexRoute
  '/$lang/virtual/$version': typeof LangLibrariesVirtualVersionIndexRoute
  '/$lang/$libraryId/$version/docs/framework/$framework/$': typeof LangLibraryIdVersionDocsFrameworkFrameworkSplatRoute
  '/$lang/$libraryId/$version/docs/framework/$framework/examples/$': typeof LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/sponsors-embed': typeof SponsorsEmbedRoute
  '/$lang/$libraryId': typeof LangLibraryIdRouteRouteWithChildren
  '/$lang': typeof LangRouteWithChildren
  '/$lang/_libraries': typeof LangLibrariesRouteRouteWithChildren
  '/$lang/$libraryId/$version': typeof LangLibraryIdVersionRouteWithChildren
  '/$lang/_libraries/blog': typeof LangLibrariesBlogRouteWithChildren
  '/$lang/_libraries/dedicated-support': typeof LangLibrariesDedicatedSupportRoute
  '/$lang/_libraries/ethos': typeof LangLibrariesEthosRoute
  '/$lang/_libraries/learn': typeof LangLibrariesLearnRoute
  '/$lang/_libraries/merch': typeof LangLibrariesMerchRoute
  '/$lang/_libraries/privacy': typeof LangLibrariesPrivacyRoute
  '/$lang/_libraries/support': typeof LangLibrariesSupportRoute
  '/$lang/_libraries/terms': typeof LangLibrariesTermsRoute
  '/$lang/$libraryId/': typeof LangLibraryIdIndexRoute
  '/$lang/_libraries/': typeof LangLibrariesIndexRoute
  '/$lang/$libraryId/$version/docs': typeof LangLibraryIdVersionDocsRouteWithChildren
  '/$lang/_libraries/blog/$': typeof LangLibrariesBlogSplatRoute
  '/$lang/_libraries/blog/': typeof LangLibrariesBlogIndexRoute
  '/$lang/$libraryId/$version/docs/$': typeof LangLibraryIdVersionDocsSplatRoute
  '/$lang/$libraryId/$version/docs/': typeof LangLibraryIdVersionDocsIndexRoute
  '/$lang/_libraries/config/$version/': typeof LangLibrariesConfigVersionIndexRoute
  '/$lang/_libraries/form/$version/': typeof LangLibrariesFormVersionIndexRoute
  '/$lang/_libraries/query/$version/': typeof LangLibrariesQueryVersionIndexRoute
  '/$lang/_libraries/ranger/$version/': typeof LangLibrariesRangerVersionIndexRoute
  '/$lang/_libraries/router/$version/': typeof LangLibrariesRouterVersionIndexRoute
  '/$lang/_libraries/start/$version/': typeof LangLibrariesStartVersionIndexRoute
  '/$lang/_libraries/store/$version/': typeof LangLibrariesStoreVersionIndexRoute
  '/$lang/_libraries/table/$version/': typeof LangLibrariesTableVersionIndexRoute
  '/$lang/_libraries/virtual/$version/': typeof LangLibrariesVirtualVersionIndexRoute
  '/$lang/$libraryId/$version/docs/framework/$framework/$': typeof LangLibraryIdVersionDocsFrameworkFrameworkSplatRoute
  '/$lang/$libraryId/$version/docs/framework/$framework/examples/$': typeof LangLibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/sponsors-embed'
    | '/$lang/$libraryId'
    | '/$lang'
    | '/$lang/$libraryId/$version'
    | '/$lang/blog'
    | '/$lang/dedicated-support'
    | '/$lang/ethos'
    | '/$lang/learn'
    | '/$lang/merch'
    | '/$lang/privacy'
    | '/$lang/support'
    | '/$lang/terms'
    | '/$lang/$libraryId/'
    | '/$lang/'
    | '/$lang/$libraryId/$version/docs'
    | '/$lang/blog/$'
    | '/$lang/blog/'
    | '/$lang/$libraryId/$version/docs/$'
    | '/$lang/$libraryId/$version/docs/'
    | '/$lang/config/$version'
    | '/$lang/form/$version'
    | '/$lang/query/$version'
    | '/$lang/ranger/$version'
    | '/$lang/router/$version'
    | '/$lang/start/$version'
    | '/$lang/store/$version'
    | '/$lang/table/$version'
    | '/$lang/virtual/$version'
    | '/$lang/$libraryId/$version/docs/framework/$framework/$'
    | '/$lang/$libraryId/$version/docs/framework/$framework/examples/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/sponsors-embed'
    | '/$lang'
    | '/$lang/$libraryId/$version'
    | '/$lang/dedicated-support'
    | '/$lang/ethos'
    | '/$lang/learn'
    | '/$lang/merch'
    | '/$lang/privacy'
    | '/$lang/support'
    | '/$lang/terms'
    | '/$lang/$libraryId'
    | '/$lang/blog/$'
    | '/$lang/blog'
    | '/$lang/$libraryId/$version/docs/$'
    | '/$lang/$libraryId/$version/docs'
    | '/$lang/config/$version'
    | '/$lang/form/$version'
    | '/$lang/query/$version'
    | '/$lang/ranger/$version'
    | '/$lang/router/$version'
    | '/$lang/start/$version'
    | '/$lang/store/$version'
    | '/$lang/table/$version'
    | '/$lang/virtual/$version'
    | '/$lang/$libraryId/$version/docs/framework/$framework/$'
    | '/$lang/$libraryId/$version/docs/framework/$framework/examples/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/sponsors-embed'
    | '/$lang/$libraryId'
    | '/$lang'
    | '/$lang/_libraries'
    | '/$lang/$libraryId/$version'
    | '/$lang/_libraries/blog'
    | '/$lang/_libraries/dedicated-support'
    | '/$lang/_libraries/ethos'
    | '/$lang/_libraries/learn'
    | '/$lang/_libraries/merch'
    | '/$lang/_libraries/privacy'
    | '/$lang/_libraries/support'
    | '/$lang/_libraries/terms'
    | '/$lang/$libraryId/'
    | '/$lang/_libraries/'
    | '/$lang/$libraryId/$version/docs'
    | '/$lang/_libraries/blog/$'
    | '/$lang/_libraries/blog/'
    | '/$lang/$libraryId/$version/docs/$'
    | '/$lang/$libraryId/$version/docs/'
    | '/$lang/_libraries/config/$version/'
    | '/$lang/_libraries/form/$version/'
    | '/$lang/_libraries/query/$version/'
    | '/$lang/_libraries/ranger/$version/'
    | '/$lang/_libraries/router/$version/'
    | '/$lang/_libraries/start/$version/'
    | '/$lang/_libraries/store/$version/'
    | '/$lang/_libraries/table/$version/'
    | '/$lang/_libraries/virtual/$version/'
    | '/$lang/$libraryId/$version/docs/framework/$framework/$'
    | '/$lang/$libraryId/$version/docs/framework/$framework/examples/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SponsorsEmbedRoute: typeof SponsorsEmbedRoute
  LangLibraryIdRouteRoute: typeof LangLibraryIdRouteRouteWithChildren
  LangRoute: typeof LangRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SponsorsEmbedRoute: SponsorsEmbedRoute,
  LangLibraryIdRouteRoute: LangLibraryIdRouteRouteWithChildren,
  LangRoute: LangRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/login",
        "/sponsors-embed",
        "/$lang/$libraryId",
        "/$lang"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/sponsors-embed": {
      "filePath": "sponsors-embed.tsx"
    },
    "/$lang/$libraryId": {
      "filePath": "$lang/$libraryId/route.tsx",
      "children": [
        "/$lang/$libraryId/$version",
        "/$lang/$libraryId/"
      ]
    },
    "/$lang": {
      "filePath": "$lang/_libraries",
      "children": [
        "/$lang/_libraries"
      ]
    },
    "/$lang/_libraries": {
      "filePath": "$lang/_libraries/route.tsx",
      "parent": "/$lang",
      "children": [
        "/$lang/_libraries/blog",
        "/$lang/_libraries/dedicated-support",
        "/$lang/_libraries/ethos",
        "/$lang/_libraries/learn",
        "/$lang/_libraries/merch",
        "/$lang/_libraries/privacy",
        "/$lang/_libraries/support",
        "/$lang/_libraries/terms",
        "/$lang/_libraries/",
        "/$lang/_libraries/config/$version/",
        "/$lang/_libraries/form/$version/",
        "/$lang/_libraries/query/$version/",
        "/$lang/_libraries/ranger/$version/",
        "/$lang/_libraries/router/$version/",
        "/$lang/_libraries/start/$version/",
        "/$lang/_libraries/store/$version/",
        "/$lang/_libraries/table/$version/",
        "/$lang/_libraries/virtual/$version/"
      ]
    },
    "/$lang/$libraryId/$version": {
      "filePath": "$lang/$libraryId/$version.tsx",
      "parent": "/$lang/$libraryId",
      "children": [
        "/$lang/$libraryId/$version/docs"
      ]
    },
    "/$lang/_libraries/blog": {
      "filePath": "$lang/_libraries/blog.tsx",
      "parent": "/$lang/_libraries",
      "children": [
        "/$lang/_libraries/blog/$",
        "/$lang/_libraries/blog/"
      ]
    },
    "/$lang/_libraries/dedicated-support": {
      "filePath": "$lang/_libraries/dedicated-support.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/ethos": {
      "filePath": "$lang/_libraries/ethos.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/learn": {
      "filePath": "$lang/_libraries/learn.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/merch": {
      "filePath": "$lang/_libraries/merch.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/privacy": {
      "filePath": "$lang/_libraries/privacy.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/support": {
      "filePath": "$lang/_libraries/support.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/terms": {
      "filePath": "$lang/_libraries/terms.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/$libraryId/": {
      "filePath": "$lang/$libraryId/index.tsx",
      "parent": "/$lang/$libraryId"
    },
    "/$lang/_libraries/": {
      "filePath": "$lang/_libraries/index.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/$libraryId/$version/docs": {
      "filePath": "$lang/$libraryId/$version.docs.tsx",
      "parent": "/$lang/$libraryId/$version",
      "children": [
        "/$lang/$libraryId/$version/docs/$",
        "/$lang/$libraryId/$version/docs/",
        "/$lang/$libraryId/$version/docs/framework/$framework/$",
        "/$lang/$libraryId/$version/docs/framework/$framework/examples/$"
      ]
    },
    "/$lang/_libraries/blog/$": {
      "filePath": "$lang/_libraries/blog.$.tsx",
      "parent": "/$lang/_libraries/blog"
    },
    "/$lang/_libraries/blog/": {
      "filePath": "$lang/_libraries/blog.index.tsx",
      "parent": "/$lang/_libraries/blog"
    },
    "/$lang/$libraryId/$version/docs/$": {
      "filePath": "$lang/$libraryId/$version.docs.$.tsx",
      "parent": "/$lang/$libraryId/$version/docs"
    },
    "/$lang/$libraryId/$version/docs/": {
      "filePath": "$lang/$libraryId/$version.docs.index.tsx",
      "parent": "/$lang/$libraryId/$version/docs"
    },
    "/$lang/_libraries/config/$version/": {
      "filePath": "$lang/_libraries/config.$version.index.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/form/$version/": {
      "filePath": "$lang/_libraries/form.$version.index.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/query/$version/": {
      "filePath": "$lang/_libraries/query.$version.index.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/ranger/$version/": {
      "filePath": "$lang/_libraries/ranger.$version.index.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/router/$version/": {
      "filePath": "$lang/_libraries/router.$version.index.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/start/$version/": {
      "filePath": "$lang/_libraries/start.$version.index.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/store/$version/": {
      "filePath": "$lang/_libraries/store.$version.index.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/table/$version/": {
      "filePath": "$lang/_libraries/table.$version.index.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/_libraries/virtual/$version/": {
      "filePath": "$lang/_libraries/virtual.$version.index.tsx",
      "parent": "/$lang/_libraries"
    },
    "/$lang/$libraryId/$version/docs/framework/$framework/$": {
      "filePath": "$lang/$libraryId/$version.docs.framework.$framework.$.tsx",
      "parent": "/$lang/$libraryId/$version/docs"
    },
    "/$lang/$libraryId/$version/docs/framework/$framework/examples/$": {
      "filePath": "$lang/$libraryId/$version.docs.framework.$framework.examples.$.tsx",
      "parent": "/$lang/$libraryId/$version/docs"
    }
  }
}
ROUTE_MANIFEST_END */
